### ISSUE TITLE
Before I do a PR - Blank Spot Cleaner

### ISSUE THREAD

**Issue by NHuebner1983** [anubiskun/fake-youtube-premium-extension#1]
I wanted to put the code here.

When running an adblocker (Tamper Monkey Script), it blocks the ads, and your YouTube Premium makes my screen all pretty.. But it's not removing the blank spots on the page, and I would like to give you my code that needs to be run at some point, I will leave that up to you - but I think you will like it!

It gets rid of the empty spaces. I think it should be changed to check TextContent length instead of the "live" and "views" I put. It could very well remove something important by accident.

I hope this contributes to your code!

I'm not trying to get recognition, just helping complete the code. You can try it from Chrome Developer Tools. It should work in all browsers:

```
setInterval(() => {document.querySelectorAll('ytd-rich-item-renderer').forEach(item => {
    if ((!item.textContent.includes('views') && !item.textContent.includes('watching'))) { item.classList.add('hidden') };
});}, 1000);
```

The interval was added so I could see it work in action as I scrolled.

On my screen, I see blank spots where advertisements used to be - heck this might also remove those ads too if it can just be detected. I hope this doesn't upset you, and good luck let me know if a PR in some way wouldn't hurt, it's been a long time since I've opened a PR on a public project.

**Comment by NHuebner1983** [comment]
feel free to resolve this issue once you receive it.

**Comment by NHuebner1983** [comment]
I hope this helps! I will use my fork since it works for my needs. Thank you.

**Comment by anubiskun** [comment]
i don't understand which part you mean, but if it helps you and it works then do a pull request,
if i execute ``document.querySelectorAll('ytd-rich-item-renderer')`` in console i don't get any class captured,
thanks for taking your time :)

**Comment by NHuebner1983** [comment]
Ah so the code is amatuer, I am a senior developer, but the code is put together slapstick (quickly).

This basically does this (see screenshot) - the ytd-rich-item-renderer is not a class, it's an element but using that query with premium it should have shifted your main display around and remove some of the additional empty spaces like.... `<ytd-rich-item-renderer>`...

![Screenshot 2024-10-07 at 12 10 08 PM](https://github.com/user-attachments/assets/3b4105bb-55cb-4d42-a579-4409358db793)

**Comment by NHuebner1983** [comment]
My main concern is that if you could possibly get my code working and see what it does (maybe compare and send a screenshot back), I need you to vet the code so that it doesn't interfere with YouTube so people don't uninstall your extension. I was hoping I would deliver the code to you and you could put it in your code. 

If you can't get it to work, let me know. It's to target each card on the YouTube feed.

Things I am concerned about:

1. The query might remove something that is not blank or is not an advertisement (this would be an edge case). Someone has to take responsibility for that, preferably the repo owner <3
2. It uses a setInterval timer, which I think might be a little "bad" compared to using some kind of "Dom" listener (this is what I meant by where to put the code in your repo).

So yeh! Other than that, combining your plugin with another script, my account is in full premium - no ads, no stress, all good!

**Comment by NHuebner1983** [comment]
So if you managed to get their script working in yours (reverse engineer, collab, etc), you could very well have one of the only working YouTube Ad Blockers - all the other ones just get you caught with "we detected an ad blocker".

Let me know if you want me to work on this more, I could do a PR that includes the tampermonkey script.

**Comment by anubiskun** [comment]
> Ah so the code is amatuer, I am a senior developer, but the code is put together slapstick (quickly).
> 
> This basically does this (see screenshot) - the ytd-rich-item-renderer is not a class, it's an element but using that query with premium it should have shifted your main display around and remove some of the additional empty spaces like.... `<ytd-rich-item-renderer>`...
> 
> ![Screenshot 2024-10-07 at 12 10 08 PM](https://private-user-images.githubusercontent.com/36468487/374248175-3b4105bb-55cb-4d42-a579-4409358db793.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjgzNDgwMzUsIm5iZiI6MTcyODM0NzczNSwicGF0aCI6Ii8zNjQ2ODQ4Ny8zNzQyNDgxNzUtM2I0MTA1YmItNTVjYi00ZDQyLWE1NzktNDQwOTM1OGRiNzkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA4VDAwMzUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyMTU4MjQ2NDA1ODJmMGNmYWYzOWRkNDVkNmEyNjQ4ODBiNjgyMmM2ZjRlNGU0ZDRmOGUxZDZlNDM0NzliNzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.wVOOUnaS0DEZf9Y8PGy_KHczy0tf1oT5JdGKahkQQdE)

aah, i got it, oke i'll try to fix them

**Comment by anubiskun** [comment]
> I honestly don't think they can block the tampermonkey script otherwise YouTube would start with an advertisement for EVERY partition of EVERY video.... This script figured it out, and it works great :) ok TTYS let me know how I can help... Still can do a PR.

if you can do that you can do PR on this repo

**Comment by anubiskun** [comment]
[anu.js#L29C1-L47C2](https://github.com/anubiskun/fake-youtube-premium-extension/blob/313e82342646cb98373295e3b2134ca16e96f89b/anu.js#L29C1-L47C2)
I have updated my code, you can check it.
